package com.aps4sem.chatclient.screens;

import com.aps4sem.chatclient.classes.User;
import com.aps4sem.chatclient.interfaces.UsersStatusListener;

public class Home extends javax.swing.JFrame implements UsersStatusListener {
    
    private final User user;
    private final String userName;
    
    public Home(User user, String userName) {
        this.user = user;
        this.userName = userName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listModel_contatos = new javax.swing.DefaultListModel();
        pn_principal = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        bt_conversar = new javax.swing.JButton();
        scroll_list_contatos = new javax.swing.JScrollPane();
        list_contatos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat - Home");
        setMinimumSize(new java.awt.Dimension(600, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_principal.setBackground(java.awt.Color.white);
        pn_principal.setLayout(null);

        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("< Usuário : " + userName + " >");
        lb_titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_principal.add(lb_titulo);
        lb_titulo.setBounds(10, 10, 580, 40);

        bt_conversar.setText("Abrir Conversa");
        pn_principal.add(bt_conversar);
        bt_conversar.setBounds(10, 430, 580, 40);

        list_contatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários Online"));
        list_contatos.setModel(listModel_contatos);
        list_contatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scroll_list_contatos.setViewportView(list_contatos);

        pn_principal.add(scroll_list_contatos);
        scroll_list_contatos.setBounds(10, 60, 580, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        user.logout();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(() -> {
            user.listenToServer(this);
        }).start();
    }//GEN-LAST:event_formWindowOpened
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_conversar;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.DefaultListModel listModel_contatos;
    private javax.swing.JList<String> list_contatos;
    private javax.swing.JPanel pn_principal;
    private javax.swing.JScrollPane scroll_list_contatos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void userOnline(String name) {
        listModel_contatos.addElement(name);
    }

    @Override
    public void userOffline(String name) {
        listModel_contatos.removeElement(name);
    }

}
