package com.aps4sem.chatclient;

import com.aps4sem.chatclient.classes.User;
import com.aps4sem.chatclient.exceptions.LoginAlreadyInUse;
import com.aps4sem.chatclient.exceptions.LoginDenied;
import com.aps4sem.chatclient.screens.Home;
import java.net.ConnectException;
import javax.swing.JOptionPane;

public class ClientMain extends javax.swing.JFrame {

    private final String SERVER_IP = "127.0.0.1";
    private final int SERVER_PORT = 9090;
    
    public ClientMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_principal = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_senha = new javax.swing.JTextField();
        bt_conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        pn_principal.setBackground(java.awt.Color.white);
        pn_principal.setLayout(null);

        lb_titulo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("CHAT");
        pn_principal.add(lb_titulo);
        lb_titulo.setBounds(10, 10, 380, 120);

        lb_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_usuario.setText("Usuário");
        lb_usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_principal.add(lb_usuario);
        lb_usuario.setBounds(10, 150, 100, 40);

        lb_senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_senha.setText("Senha");
        lb_senha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_principal.add(lb_senha);
        lb_senha.setBounds(10, 200, 100, 40);
        pn_principal.add(tf_usuario);
        tf_usuario.setBounds(120, 150, 270, 40);
        pn_principal.add(tf_senha);
        tf_senha.setBounds(120, 200, 270, 40);

        bt_conectar.setText("Conectar");
        bt_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conectarActionPerformed(evt);
            }
        });
        pn_principal.add(bt_conectar);
        bt_conectar.setBounds(10, 250, 380, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conectarActionPerformed
        
        try {
            String userName = tf_usuario.getText();
            String password = tf_senha.getText();
            
            User user = new User(SERVER_IP, SERVER_PORT, userName, password);
            
            new Home(user, userName).setVisible(true);
            this.dispose();
        }
        catch (ConnectException ex) {
            JOptionPane.showMessageDialog(this, "Verifique se o servidor está em execução!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        catch (LoginDenied ex) {
            JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        catch (LoginAlreadyInUse ex) {
            JOptionPane.showMessageDialog(this, "Este usuário já está logado no servidor.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_conectarActionPerformed

    public static void main(String[] args) {
        new ClientMain().setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_conectar;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel pn_principal;
    private javax.swing.JTextField tf_senha;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables

}
