package com.aps4sem.chatclient;

import com.aps4sem.chatlibrary.*;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    private static final String SERVER_IP = "127.0.0.1";
    private static final int SERVER_PORT = 9090;
    
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_principal = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        lb_porta = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_porta = new javax.swing.JTextField();
        bt_conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        pn_principal.setBackground(java.awt.Color.white);
        pn_principal.setLayout(null);

        lb_titulo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("CHAT");
        pn_principal.add(lb_titulo);
        lb_titulo.setBounds(10, 10, 380, 120);

        lb_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_usuario.setText("Apelido");
        lb_usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_principal.add(lb_usuario);
        lb_usuario.setBounds(10, 150, 100, 40);

        lb_porta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_porta.setText("Porta");
        lb_porta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_principal.add(lb_porta);
        lb_porta.setBounds(10, 200, 100, 40);
        pn_principal.add(tf_usuario);
        tf_usuario.setBounds(120, 150, 270, 40);
        pn_principal.add(tf_porta);
        tf_porta.setBounds(120, 200, 270, 40);

        bt_conectar.setText("Conectar");
        bt_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conectarActionPerformed(evt);
            }
        });
        pn_principal.add(bt_conectar);
        bt_conectar.setBounds(10, 250, 380, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conectarActionPerformed
        
        try {
            Socket serverSocket = new Socket(SERVER_IP, SERVER_PORT);
            SocketObjectStreams streams = new SocketObjectStreams(serverSocket);
            
            String user = tf_usuario.getText();
            String password = tf_porta.getText();
            
            streams.send(ClientRequest.LOGIN);
            streams.send(new String[] {user, password});
            
            ServerResponse response = (ServerResponse) streams.receive();
            
            switch (response)
            {
                case LOGIN_ALLOWED:
                    JOptionPane.showMessageDialog(null, "Bem-vindo!", "", JOptionPane.OK_OPTION);
                    break;
                case LOGIN_DENIED:
                    JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos.", "Erro", JOptionPane.ERROR_MESSAGE);
                    break;
            }
            
            tf_usuario.setText("");
            tf_porta.setText("");
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Verifique se o servidor está em execução!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_conectarActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_conectar;
    private javax.swing.JLabel lb_porta;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel pn_principal;
    private javax.swing.JTextField tf_porta;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables

}
